import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "@/styles/Home.module.css"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {

	return (
		<div >
			<Head>
				<title>PGF</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="banner">
				<div className="wrap">
					<img src="https://ezvdrqbu3wydntjk2fsrq2ylp4opmrjlrzexirj2s7ezgan5da6q.arweave.net/Jmo4wDTdsDbNKtFlGGsLfxz2RSuOSXRFOpfJkwG9GD0?ext=png" alt="" />
				</div>
				<div className="centered">
					<h1>
						NFT GALLERY
					</h1>
					<h3>
						Collection
					</h3>
				</div>
			</div>

			<div className="main">
				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>


				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>


				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>


				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>

				<div className="card">
					<div className="card_head">
						<div className="card_product-img">
							<img src="https://www.cnet.com/a/img/resize/f6c7acae69061033904163bfd7e3bd0a28158be5/hub/2022/06/06/1e434c1e-e76f-47d3-9365-444ae1e4bddf/screen-shot-2022-06-06-at-11-32-02-am.jpg?auto=webp" alt="" />
						</div>
					</div>

					<div className="card_body">
						<a className="card_title" href="">
							<h3>Number #3737</h3>
						</a>

						<p className="card_text">The description</p>

						<div className="wrapper">
							<div className="card_price">
								<span>0.03 ETH</span>
							</div>
							<div className="card_countdown">
								<span>3 Days Left</span> 
							</div>
						</div>

					</div>

					<div className="card_footer">
						<img className="author-img" src="https://m.media-amazon.com/images/I/5118mkJR64L.jpg" alt="" />
						<p className="author_name">Name</p>
					</div>
				</div>
			</div>

			
		</div>
	)
}
